# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a70q/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a70q

PRODUCT_COPY_FILES += \
    vendor/samsung/a70q/proprietary/etc/bluetooth/av_performance.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/bluetooth/av_performance.conf \
    vendor/samsung/a70q/proprietary/etc/bluetooth/iop_bt.db:$(TARGET_COPY_OUT_SYSTEM)/etc/bluetooth/iop_bt.db \
    vendor/samsung/a70q/proprietary/etc/firmware/nvm_tlv.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv.bin \
    vendor/samsung/a70q/proprietary/etc/firmware/nvm_tlv_1.3.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv_1.3.bin \
    vendor/samsung/a70q/proprietary/etc/firmware/nvm_tlv_2.1.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv_2.1.bin \
    vendor/samsung/a70q/proprietary/etc/firmware/nvm_tlv_3.0.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv_3.0.bin \
    vendor/samsung/a70q/proprietary/etc/firmware/nvm_tlv_3.2.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv_3.2.bin \
    vendor/samsung/a70q/proprietary/etc/firmware/rampatch_tlv.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv.img \
    vendor/samsung/a70q/proprietary/etc/firmware/rampatch_tlv_1.3.tlv:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv_1.3.tlv \
    vendor/samsung/a70q/proprietary/etc/firmware/rampatch_tlv_2.1.tlv:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv_2.1.tlv \
    vendor/samsung/a70q/proprietary/etc/firmware/rampatch_tlv_3.0.tlv:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv_3.0.tlv \
    vendor/samsung/a70q/proprietary/etc/firmware/rampatch_tlv_3.2.tlv:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv_3.2.tlv \
    vendor/samsung/a70q/proprietary/etc/pdp_copycache.sh:$(TARGET_COPY_OUT_SYSTEM)/etc/pdp_copycache.sh \
    vendor/samsung/a70q/proprietary/etc/pdp_papps_copy.sh:$(TARGET_COPY_OUT_SYSTEM)/etc/pdp_papps_copy.sh \
    vendor/samsung/a70q/proprietary/etc/pdp_prepare_fbe.sh:$(TARGET_COPY_OUT_SYSTEM)/etc/pdp_prepare_fbe.sh \
    vendor/samsung/a70q/proprietary/etc/pdp_restore.sh:$(TARGET_COPY_OUT_SYSTEM)/etc/pdp_restore.sh \
    vendor/samsung/a70q/proprietary/etc/pdp_saveplog.sh:$(TARGET_COPY_OUT_SYSTEM)/etc/pdp_saveplog.sh
